### ISSUE TITLE
Add support for manual steps, that can be triggered from the UI

### ISSUE THREAD

**Issue by supernova32** [AlloyCI/alloy_ci#20]
For deployments, it would be good to also allow manual steps, not just automatic steps. This way, you can deploy only if a button is clicked.

The definition of what a manual job is under GitLab can be found [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/ci/yaml/README.md#whenmanual). 

A manual job is specified on the `when` directive of the build job, its default value for` allow_failure` is `true` and if execution of the rest of the pipeline should be stopped until this job finishes, it should be set to `false`.

### Tasks

- [x] Handle the `manual` option on the `when` directive
- [x] Block pipeline execution when required
- [ ] Show the manual step as a manual step on the UI
- [ ] Add actions to start the manual step
- [ ] If the manual step depends on other builds, don't mark it as startable unless all requirements are fulfilled
- [ ] Make the UI nice 

Might depend on #2
